name: healthtrackerapp
description: A real food scanner and nutrition tracker built with Flutter, Firebase, and Gemini AI.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & Charts
  cupertino_icons: ^1.0.6
  fl_chart: ^0.66.0

  # Firebase Core and SDKs
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # official Gemini AI SDK
  google_generative_ai: ^0.2.2

  # Live Camera hardware utilities
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/